"""Tests for lockcheck: does the running process match the hashed lock?"""
from __future__ import annotations

from pathlib import Path

import pytest

import lockcheck

LOCK = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.in --universal --python-version 3.11 --generate-hashes -o requirements.txt
alpha==1.2.3 \\
    --hash=sha256:aaaa \\
    --hash=sha256:bbbb
    # via -r requirements.in
beta-pkg==2.0 ; sys_platform == 'emscripten' \\
    --hash=sha256:cccc
gamma==0.1.0 \\
    --hash=sha256:dddd
"""


def _write(tmp_path: Path, text: str = LOCK) -> Path:
    path = tmp_path / "requirements.txt"
    path.write_text(text, encoding="utf-8")
    return path


def _installed(**versions: str):
    def lookup(name: str) -> str | None:
        return versions.get(name)
    return lookup


class TestLockedPins:
    def test_reads_names_versions_and_markers_only(self) -> None:
        assert lockcheck.locked_pins(LOCK) == [
            ("alpha", "1.2.3", False),
            ("beta-pkg", "2.0", True),
            ("gamma", "0.1.0", False),
        ]

    def test_ignores_comments_hashes_and_blank_lines(self) -> None:
        assert lockcheck.locked_pins("# x==1\n    --hash=sha256:a\n\n") == []


class TestDependenciesLocked:
    def test_true_when_every_pin_matches(self, tmp_path) -> None:
        installed = _installed(alpha="1.2.3", gamma="0.1.0")

        assert lockcheck.dependencies_locked(_write(tmp_path), installed) is True

    def test_false_when_a_version_differs(self, tmp_path) -> None:
        installed = _installed(alpha="1.2.4", gamma="0.1.0")

        assert lockcheck.dependencies_locked(_write(tmp_path), installed) is False

    def test_false_when_an_unmarked_pin_is_missing(self, tmp_path) -> None:
        installed = _installed(alpha="1.2.3")

        assert lockcheck.dependencies_locked(_write(tmp_path), installed) is False

    def test_a_marked_pin_that_is_absent_is_taken_as_excluded(self, tmp_path) -> None:
        installed = _installed(alpha="1.2.3", gamma="0.1.0")

        assert lockcheck.dependencies_locked(_write(tmp_path), installed) is True

    def test_a_marked_pin_installed_at_another_version_is_a_mismatch(
        self, tmp_path
    ) -> None:
        installed = _installed(alpha="1.2.3", **{"beta-pkg": "2.1"}, gamma="0.1.0")

        assert lockcheck.dependencies_locked(_write(tmp_path), installed) is False

    def test_false_when_the_lock_is_missing(self, tmp_path) -> None:
        assert lockcheck.dependencies_locked(
            tmp_path / "nope.txt", _installed(alpha="1.2.3")
        ) is False

    def test_false_when_the_lock_has_no_pins(self, tmp_path) -> None:
        assert lockcheck.dependencies_locked(_write(tmp_path, "# empty\n"), _installed()) is False

    def test_the_real_lock_has_pins_for_every_top_level_requirement(self) -> None:
        """The shipped lock is a real uv lock this parser understands."""
        names = {name for name, _, _ in lockcheck.locked_pins(
            lockcheck.LOCK_PATH.read_text(encoding="utf-8"))}
        for top in ("fastapi", "uvicorn", "sqlalchemy", "anthropic", "alembic"):
            assert top in names

    @pytest.mark.parametrize("name", ["pydantic-core", "pydantic_core", "Pydantic-Core"])
    def test_the_default_lookup_normalises_names(self, name: str) -> None:
        assert lockcheck._installed_version(name) is not None
