"""Alembic environment for the SOCTriage backend.

The database URL is not configured here or in alembic.ini. It comes from
database.DATABASE_URL, which is resolved exactly as the application resolves
it: DATABASE_URL from the environment (or backend/.env), the legacy
"postgres://" scheme rewritten, and a local SQLite file when it is unset. So
`alembic upgrade head` always targets the database the app would use.

Two ways in:

- The alembic CLI, run from backend/. Opens its own connection.
- database.init_db() on application startup, which passes its connection in
  through config.attributes["connection"] so the upgrade runs inside the app's
  transaction and does not reconfigure the app's logging.
"""
from logging.config import fileConfig

from alembic import context
from dotenv import load_dotenv
from sqlalchemy import Connection, create_engine, make_url, pool

# The CLI does not go through main.py, so load backend/.env here too; without
# it a developer's `alembic upgrade head` would silently target SQLite while the
# app targets the Postgres named in .env. Never overrides a variable that is
# already set, so CI and Railway are unaffected.
load_dotenv()

from database import DATABASE_URL, Base  # noqa: E402

config = context.config
target_metadata = Base.metadata

_external_connection: Connection | None = config.attributes.get("connection")

# Only configure logging for the CLI. Called from inside the app, fileConfig
# would replace the app's handlers and disable its existing loggers (the audit
# logger among them).
if _external_connection is None and config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)


def _configure_kwargs(dialect_name: str) -> dict:
    # SQLite cannot ALTER most things in place; batch mode makes autogenerated
    # migrations rebuild the table instead, so they run on both backends.
    return {"target_metadata": target_metadata, "render_as_batch": dialect_name == "sqlite"}


def run_migrations_offline() -> None:
    """Emit SQL to stdout (`alembic upgrade head --sql`) without connecting."""
    context.configure(
        url=DATABASE_URL,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        **_configure_kwargs(make_url(DATABASE_URL).get_backend_name()),
    )
    with context.begin_transaction():
        context.run_migrations()


def _run_with(connection: Connection) -> None:
    context.configure(connection=connection, **_configure_kwargs(connection.dialect.name))
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    if _external_connection is not None:
        _run_with(_external_connection)
        return
    connectable = create_engine(DATABASE_URL, poolclass=pool.NullPool)
    with connectable.connect() as connection:
        _run_with(connection)


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
