"""baseline cases table

Revision ID: 0001
Revises:
Create Date: 2026-09-27 23:11:34.964504

The schema as Base.metadata.create_all() built it before migrations existed:
the one `cases` table from database.CaseRow, with its status and severity
indexes. Autogenerated against an empty database, then checked column by
column against the model.

A database created before this migration existed already has exactly this
table, so database.init_db() stamps it at this revision instead of running it.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('cases',
    sa.Column('case_id', sa.String(length=16), nullable=False),
    sa.Column('ioc', sa.Text(), nullable=False),
    sa.Column('ioc_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('enrichment', sa.JSON(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index('ix_cases_severity', 'cases', ['severity'], unique=False)
    op.create_index('ix_cases_status', 'cases', ['status'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_cases_status', table_name='cases')
    op.drop_index('ix_cases_severity', table_name='cases')
    op.drop_table('cases')
